services:
  - type: web
    name: delowyss-trading
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: IQ_EMAIL
        value: tu_correo_iqoption@example.com
      - key: IQ_PASSWORD
        value: tu_password_segura
